services:
  autonomous_surgery:

    image: autonomous_surgery:latest
    container_name: autonomous_surgery_dev

    network_mode: host
    ipc: host

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      # ---------------- ROS Networking ----------------
      - ROS_MASTER_URI=http://10.162.34.59:11311   # <-- CHANGE THIS
      - ROS_IP=10.162.34.58                        # <-- CHANGE THIS
      # ------------------------------------------------

      - SSH_AUTH_SOCK=/ssh-agent
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - HF_HOME=/workspace/.hf
      - HF_TOKEN=${HF_TOKEN}

    volumes:
      - ./:/workspace
      - conda_envs:/opt/conda/envs
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ./.hf:/.hf

    working_dir: /workspace
    stdin_open: true
    tty: true
    command: bash

volumes:
  conda_envs: