name: CholecystectomyACTGraspOnlyDebug

dataset_instantiate_config:
  _target_: autonomous_surgery.dataset.Debug
  repo_id: surpass/cholecystectomy_accelerated
  root: /home/byrdgb1/surpass/.hf/lerobot/surpass/cholecystectomy_accelerated
  tolerance_s: 1e-4