name: CholecystectomyACTGraspOnlyDebug

dataset_instantiate_config:
  _target_: autonomous_surgery.dataset.Debug
  repo_id: surpass/cholecystectomy_dummy
  root: /home/grayson/surpass/.hf/lerobot/surpass/cholecystectomy_dummy
  tolerance_s: 1e-4